name: Test on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build
        run: |
          make clean
          CXX=g++ make
          
      - name: Inspect library
        run: |
          ls -l shared/
          file shared/libjsonparser.so
          nm -C shared/libjsonparser.so | grep 'JSON_Parser'
          nm -C shared/libjsonparser.so | grep 'JSON_Node::operator'
          nm -C shared/libjsonparser.so | grep 'JSON_Value::JSON_Value'

      - name: Run
        run: |
          CXX=g++ make run
